### ISSUE TITLE
Tag/release MITK-ProjectTemplate with version numbers that match MITK releases

### ISSUE THREAD

**Issue by nocnokneo** [MITK/MITK-ProjectTemplate#5]
Otherwise it's impossible to know if you're getting a version of MITK-ProjectTemplate that was meant for the version of MITK being used.

**Comment by saschazelzer** [comment]
We do this already, which can be seen here: https://github.com/MITK/MITK-ProjectTemplate/releases. Or do you have something else in mind?

**Comment by nocnokneo** [comment]
So weird - I thought I checked that page for tags/releases yesterday and saw nothing... I guess it's time to go back to an afternoon cup of coffee! Sorry for the trouble.
