### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by itcthienkhiem** [MITK/MITK-ProjectTemplate#6]
hi all, 
how fix it ?
thank so much
![capture](https://cloud.githubusercontent.com/assets/2140355/13204136/01553974-d87d-11e5-8acd-e65ee6ce5cfd.PNG)

**Comment by itcthienkhiem** [comment]
![2](https://cloud.githubusercontent.com/assets/2140355/13204144/3d26eac4-d87d-11e5-8fc5-67137ac86ac2.PNG)

**Comment by kislinsk** [comment]
Closed because most probably outdated.
